# Generated by Django 5.0 on 2025-01-05 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead_last_contacted_lead_next_followup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
