# Generated by Django 5.0 on 2025-01-05 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lead_completed_at_lead_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstatushistory',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.lead'),
        ),
    ]
