# Generated by Django 5.0 on 2025-01-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_lead_options_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfollowup',
            name='communication_type',
            field=models.CharField(choices=[('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('WHATSAPP', 'WhatsApp')], default='CALL', max_length=20),
        ),
    ]
