# Generated by Django 5.0 on 2025-01-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lead_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={},
        ),
        migrations.RemoveField(
            model_name='lead',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='leadfollowup',
            name='communication_type',
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='core_lead_assigne_1528df_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['task'], name='core_lead_task_id_6e496d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='core_lead_status_7318b1_idx'),
        ),
    ]
