# Generated by Django 5.0 on 2025-02-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_lead_options_remove_lead_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
